---
title: "Schedule"
---

## Day 1 -- Introduction to R (optional) -- [18<sup>th</sup> March]{style="font-size: 67%;"}

| Time        | Activity          | led by |
|-------------|-------------------|--------|
| 09:30-09:45 | Welcome           | Team   |
| 09:45-10:30 | Introduction to R |        |
| 10:45-11:15 | Coffee Break      |        |
| 11:15-12:30 | Introduction to R |        |
| 12:30-13:30 | Lunch Break       |        |
| 13:30-15:00 | Introduction to R |        |
| 15:00-15:30 | Coffee Break      |        |
| 15:30-17:00 | Introduction to R |        |
| 17:00-18:00 | Icebreaker        |        |
| 18:00       | Dinner at ?       |        |

## Day 2 -- StratoBayes: Correlation and age modelling -- [19<sup>th</sup> March]{style="font-size: 67%;"}

| Time        | Activity                                       | led by             |
|-------------|------------------------------------------------|--------------------|
| 09:00-09:15 | Welcome and introductions                      | Team               |
| 09:15-10:00 | Stratigraphic data and correlation             | Matthias Sinnesael |
| 10:00-10:45 | Getting started with the StratoBayes R package | Kilian Eichenseer  |
| 10:45-11:15 | Coffee Break                                   |                    |
| 11:00-11:45 | Bayesian age modelling                         | Andrew Millard     |
| 11:45-12:30 |                                                |                    |
| 12:30-13:30 | Lunch Break                                    |                    |
| 14:00-15:30 |                                                |                    |
| 15:30-16:00 | Coffee Break                                   |                    |
| 16:00-17:30 |                                                |                    |

## Day 3 -- Delegate project work -- [20<sup>th</sup> March]{style="font-size: 67%;"}

| Time        | Activity                              |     |
|-------------|---------------------------------------|-----|
| 09:00-09:45 | Participants introduce their projects |     |
| 09:45-10:30 | Individual project work               |     |
| 10:30-11:00 | Coffee break                          |     |
| 10:30-12:30 | Individual project work               |     |
| 12:30-13:30 | Lunch Break                           |     |
| 13:30-13:45 | quick updates on progress             |     |
| 13:45-15:00 | Individual project work               |     |
| 15:30-16:00 | Coffee Break                          |     |
| 16:00-16:30 | Preparing results                     |     |
| 16:30-17:30 | Presenting & discussing results       |     |

```{=html}
<script>
document.addEventListener('DOMContentLoaded', (event) => {
  let tables = document.querySelectorAll('table');
  tables.forEach(table => table.classList.add('table-schedule'));
});
</script>
```
